export const constants = {
  startMessage: "Hello Coder, great to have you on board! Let's get started: type /help to get the list of all the possible commands.\n",
  helpMessage: 'Here are the basic list of commands that you can use:\n\n/sites - To get the information on upcoming & running contests from all the available websites.\n\n/upcoming - To get all the upcoming contests from all the websites.\n\n/running - To get all the running contests from all the websites.\n\n/subscribe - Subscribe to get a reminder of upcoming contests from all the websites, a day and an hour before it begins!\n\n/more - Connect with the community & the developers of this bot!\n\n/contribute - To know more about contributing to this project.',
  sitesMessage: 'Here are the websites from which the contests will be listed from: \n\n1. Codeforces\n    /cf_upcoming - To get all the upcoming contests on CodeForces.\n    /cf_running - To get all the running contests on CodeForces. \n\n2. CodeChef\n    /cc_upcoming - To get all the upcoming contests on CodeChef.\n    /cc_running - To get all the running contests on CodeChef. \n\n3. Atcoder\n    /ac_contests - To get all the contests from AtCoder.\n\n4. Google Kick Start \n    /ks_contests - To get all the contests from Google KickStart.',
  miscReplyUpcoming: 'All the upcoming events from the websites are listed below - ',
  miscReplyRunning: 'All the running events from the websites are listed below - ',
  codeForcesUrl: 'https://codeforces.com/api/contest.list',
  codeForcesErr: 'Oops, looks like there are no upcoming contests currently on Codeforces.',
  codeForcesReplyUpcoming: 'Upcoming contests on Codeforces are - ',
  codeForcesReplyRunning: 'Running contests on Codeforces are - ',
  codeChefUrlUpcoming: 'https://api.codechef.com/contests?status=future&sortOrder=asc',
  codeChefUrlRunning: 'https://api.codechef.com/contests?status=present&sortOrder=asc',
  codeChefErr: 'Oops, looks like there are no upcoming contests currently on CodeChef.',
  codeChefReplyUpcoming: 'Upcoming contests on CodeChef are - ',
  codeChefReplyRunning: 'Running contests on CodeChef are - ',
  atCoderUrl: `${process.env.ATCODER_URL}/api/v1/atcoder`,
  atCoderErr: 'Oops, looks like there are no upcoming contests currently on Atcoder.',
  atCoderReply: 'Upcoming contests on Atcoder are - ',
  noContestMessage: 'Sorry, looks like there are no running contests right now!',
  codeChefTokenUrl: 'https://api.codechef.com/oauth/token',
  kickStartReply: 'Upcoming contests on Google KickStart are - (GMT +5:30)',
  knowMore: '/community - To know more about the community - Developers Students Club, VIT Vellore. \n\n/devs - To know more about the developers!',
  contributeMessage: 'Contribute to this project to make it bigger and better :) \n\nRepo link: https://github.com/GDGVIT/code-competition-watcher\n\nMake Open Source Programming fun and Happy Developing! 👩‍💻👨‍💻 ',
  communityMessage: 'We are a group of passionate designers, developers and managers who work together to bring about collaborative results that better the lives of everyone around us.\n\n',
  devsMessage: 'Meet the devs!\n\n'
}
